final Map<String, dynamic> sampleProperty = {
  "_id": "propertyId123",
  "userId": "user456",
  "title": "Modern Studio Apartment in Molyko",
  "description":
      "A modern self-contained studio apartment, fully tiled, located just 2 mins from Checkpoint junction.",
  "images": [
    "https://images.pexels.com/photos/8146320/pexels-photo-8146320.jpeg",
    "https://images.pexels.com/photos/8146321/pexels-photo-8146321.jpeg",
  ],
  "videos": ["https://cdn.snaprent.com/property123/tour.mp4"],
  // "location": {
  //   "type": "Point",
  //   "coordinates": [9.248, 4.158], // [longitude, latitude]
  //   "town": "Buea",
  //   "quarter": "Molyko",
  //   "street": "Checkpoint Street",
  //   "landmark": "Opposite Orange Shop",
  // },
  "type": "studio",
  "floorLevel": 2,
  "size": "25m²",
  "rentAmount": 35000,
  "currency": "FCFA",
  "paymentFrequency": "monthly",
  "securityDeposit": 20000,
  "amenities": {
    "toilet": "private",
    "bathroom": "private",
    "kitchen": "private",
    "furnished": false,
    "waterAvailable": true,
    "electricity": true,
    "meterType": "prepaid",
    "internet": true,
    "parking": false,
    "balcony": true,
    "ceilingFan": false,
    "tiledFloor": true,
  },
  "houseRules": {
    "smokingAllowed": false,
    "petsAllowed": false,
    "quietHours": "10 PM - 6 AM",
    "visitorsAllowed": true,
  },
  // "contact": {
  //   "phone": "+237690123456",
  //   "whatsapp": "+237690123456",
  //   "agentName": "Mr. Bate",
  // },
  "viewCount": 100,
  "status": true,
  "createdAt": "2025-08-01T09:00:00Z",
  "expiresAt": "2025-08-31T09:00:00Z",
};
